packages:
  - 'apps/*'
  - 'packages/*'
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@sentry/cli'
  - '@swc/core'
  - 'esbuild'
  - 'prisma'
  - 'sharp'
  - 'unrs-resolver'
verifyDepsBeforeRun: false
